### ISSUE TITLE
Add client package

### ISSUE THREAD

**Issue by csaba-nagy** [nandordudas/build-todo-app#29]
### Create client-side package

As a developer, I want to create a proper client package which uses the previously created API services.

**To-Do List:**
- [ ] Create a React based app with TypeScript using Vite
- [ ] Setup redux-toolkit
- [ ] Make API calls with thunks
- [ ] Implement state management
- [ ] Finish the UI
